<script setup lang="ts">
import type { CatalogItem } from "@catalog/shared";
type Detail = CatalogItem & { history: Array<{ observed_date: string; min_price: number; max_price: number; last_price: number; source_lpl_30: number | null }> };
const route = useRoute(); const api = useApi(); const product = ref<Detail | null>(null); const error = ref("");
const format = (value: number | null) => value === null ? "—" : new Intl.NumberFormat("lt-LT", { style: "currency", currency: product.value?.currency || "EUR" }).format(value / 100);
onMounted(async () => { try { product.value = await api<Detail>(`/v1/products/${route.params.id}`); } catch (cause) { error.value = cause instanceof Error ? cause.message : "Produkto užkrauti nepavyko"; } });
</script>

<template><main class="detail-page"><NuxtLink to="/" class="back">← Grįžti į katalogą</NuxtLink><p v-if="error" class="error-state">{{ error }}</p><section v-else-if="product" class="detail-grid"><div class="detail-image"><img v-if="product.imageUrls[0]" :src="product.imageUrls[0]" :alt="product.name"></div><div><p class="eyebrow">{{ product.brand }}</p><h1>{{ product.name }}</h1><p class="detail-price">{{ format(product.currentPrice) }}</p><p v-if="product.originalPrice"><s>{{ format(product.originalPrice) }}</s></p><dl><div><dt>30 d. mūsų minimumas</dt><dd>{{ format(product.observedMin30d) }}</dd></div><div><dt>Šaltinio LPL</dt><dd>{{ format(product.sourceLpl30) }}</dd></div><div><dt>Spalva</dt><dd>{{ product.colorOriginal || product.colorFamily }}</dd></div></dl><a :href="product.productUrl" target="_blank" rel="noopener noreferrer" class="primary external">Atidaryti ABOUT YOU ↗</a></div></section><section v-if="product?.history.length" class="history"><h2>Kainos istorija</h2><div class="history-list"><div v-for="day in product.history" :key="day.observed_date"><time>{{ day.observed_date }}</time><strong>{{ format(day.min_price) }}</strong><span>dienos max. {{ format(day.max_price) }}</span></div></div></section></main></template>

