<script setup lang="ts">
type Target = { id: string; label: string; url: string; kind: string; enabled: boolean; priority: number; last_success_at: string | null; last_error: string | null };
type Run = { id: string; status: string; started_at: string; products_count: number; error: string | null; sync_targets?: { label: string } };
const api = useApi(); const targets = ref<Target[]>([]); const runs = ref<Run[]>([]); const error = ref("");
const form = reactive({ label: "", url: "", kind: "category", priority: 100, enabled: true });
async function refresh() { try { [targets.value, runs.value] = await Promise.all([api<Target[]>("/v1/sync-targets"), api<Run[]>("/v1/sync-runs")]); } catch (cause) { error.value = cause instanceof Error ? cause.message : "Duomenų užkrauti nepavyko"; } }
async function add() { await api("/v1/sync-targets", { method: "POST", body: form }); Object.assign(form, { label: "", url: "", kind: "category", priority: 100, enabled: true }); await refresh(); }
async function toggle(target: Target) { await api(`/v1/sync-targets/${target.id}`, { method: "PATCH", body: { enabled: !target.enabled } }); await refresh(); }
async function queue(target: Target) { await api(`/v1/sync-targets/${target.id}/request-sync`, { method: "POST" }); await refresh(); }
onMounted(refresh);
</script>

<template><main class="admin-page"><div class="page-title"><p class="eyebrow">ADMINISTRAVIMAS</p><h1>Sinchronizavimo grupės</h1></div><p v-if="error" class="error-state">{{ error }}</p><section class="admin-panel"><h2>Pridėti grupę</h2><form class="target-form" @submit.prevent="add"><label>Pavadinimas<input v-model="form.label" required></label><label>Tipas<select v-model="form.kind"><option value="category">Kategorija</option><option value="brand">Brandas</option><option value="search">Paieška</option></select></label><label class="wide">ABOUT YOU URL<input v-model="form.url" type="url" required placeholder="https://www.aboutyou.lt/c/..."></label><button class="primary">Pridėti</button></form></section><section class="admin-panel"><h2>Aktyvios grupės</h2><div class="table-wrap"><table><thead><tr><th>Grupė</th><th>Būsena</th><th>Paskutinis atnaujinimas</th><th>Veiksmai</th></tr></thead><tbody><tr v-for="target in targets" :key="target.id"><td><strong>{{ target.label }}</strong><small>{{ target.url }}</small></td><td><span class="status" :class="target.enabled ? 'success' : ''">{{ target.enabled ? "Aktyvi" : "Išjungta" }}</span><small v-if="target.last_error" class="error">{{ target.last_error }}</small></td><td>{{ target.last_success_at ? new Date(target.last_success_at).toLocaleString('lt-LT') : '—' }}</td><td><button class="text-action" @click="queue(target)">Į eilę</button><button class="text-action" @click="toggle(target)">{{ target.enabled ? "Išjungti" : "Įjungti" }}</button></td></tr></tbody></table></div></section><section class="admin-panel"><h2>Paskutiniai darbai</h2><div class="run-list"><div v-for="run in runs.slice(0, 20)" :key="run.id"><span class="status" :class="run.status">{{ run.status }}</span><strong>{{ run.sync_targets?.label }}</strong><time>{{ new Date(run.started_at).toLocaleString('lt-LT') }}</time><span>{{ run.products_count }} produktų</span></div></div></section></main></template>

