/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 686f97e3343b2f0462c0063726a63797)
interface __BaseEnv_Env {
	ALLOWED_ORIGIN: "http://localhost:3000";
	GITHUB_OWNER: "mokinys98";
	GITHUB_REPO: "AboutYou";
	GITHUB_REF: "main";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_REF">> {}
}
