/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f19c31544d93af23d76fd25ef219081c)
interface __BaseEnv_Env {
	ALLOWED_ORIGIN: "https://staging-preview.aboutyou-private-catalog-web.pages.dev,http://localhost:3000,http://localhost:3001,http://localhost:3002" | "https://aboutyou-private-catalog-web.pages.dev";
	WEB_APP_URL: "https://staging-preview.aboutyou-private-catalog-web.pages.dev" | "https://aboutyou-private-catalog-web.pages.dev";
	TELEGRAM_BOT_USERNAME: "AboutYouTrackerBot";
	GITHUB_OWNER: "mokinys98";
	GITHUB_REPO: "AboutYou";
	GITHUB_REF: "main";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		ALLOWED_ORIGIN: "https://staging-preview.aboutyou-private-catalog-web.pages.dev,http://localhost:3000,http://localhost:3001,http://localhost:3002";
		WEB_APP_URL: "https://staging-preview.aboutyou-private-catalog-web.pages.dev";
		TELEGRAM_BOT_USERNAME: "AboutYouTrackerBot";
		GITHUB_OWNER: "mokinys98";
		GITHUB_REPO: "AboutYou";
		GITHUB_REF: "main";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "WEB_APP_URL" | "TELEGRAM_BOT_USERNAME" | "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_REF">> {}
}
