/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b2e7d6c1db5681b8f9516b8dedd98263)
interface __BaseEnv_Env {
	ALLOWED_ORIGIN: "https://staging-preview.aboutyou-private-catalog-web.pages.dev,http://localhost:3000,http://localhost:3001,http://localhost:3002" | "https://aboutyou-private-catalog-web.pages.dev,https://rinkissaupigiausia.online";
	WEB_APP_URL: "https://staging-preview.aboutyou-private-catalog-web.pages.dev" | "https://rinkissaupigiausia.online";
	TELEGRAM_BOT_USERNAME: "AboutYouTrackerBot";
	GITHUB_OWNER: "mokinys98";
	GITHUB_REPO: "AboutYou";
	GITHUB_REF: "main";
	AI_ENRICHMENT_ENABLED: "false";
	AI_CRON_ENABLED: "false";
	AI_INCENTIVE_VERIFIED: "false";
	AI_DAILY_TOKEN_CAP: "200000";
}
declare namespace Cloudflare {
	interface StagingEnv {
		ALLOWED_ORIGIN: "https://staging-preview.aboutyou-private-catalog-web.pages.dev,http://localhost:3000,http://localhost:3001,http://localhost:3002";
		WEB_APP_URL: "https://staging-preview.aboutyou-private-catalog-web.pages.dev";
		TELEGRAM_BOT_USERNAME: "AboutYouTrackerBot";
		GITHUB_OWNER: "mokinys98";
		GITHUB_REPO: "AboutYou";
		GITHUB_REF: "main";
		AI_ENRICHMENT_ENABLED: "false";
		AI_CRON_ENABLED: "false";
		AI_INCENTIVE_VERIFIED: "false";
		AI_DAILY_TOKEN_CAP: "200000";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "WEB_APP_URL" | "TELEGRAM_BOT_USERNAME" | "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_REF" | "AI_ENRICHMENT_ENABLED" | "AI_CRON_ENABLED" | "AI_INCENTIVE_VERIFIED" | "AI_DAILY_TOKEN_CAP">> {}
}
